//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public Aluno()
        {
            this.AlunosAssEsts = new HashSet<AlunosAssEst>();
        }
    
        public int NumAl { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<AlunosAssEst> AlunosAssEsts { get; set; }
    }
}
