// <auto-generated />
namespace ASIVesteLoja.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class V8_Reclamacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V8_Reclamacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201402060008533_V8_Reclamacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
