// <auto-generated />
namespace ASIVesteLoja.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class V5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V5));
        
        string IMigrationMetadata.Id
        {
            get { return "201402021959430_V5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
