//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex4Cliente.b.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServico", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IServico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/TransferirSessionFull", ReplyAction="http://tempuri.org/IServico/TransferirSessionFullResponse")]
        void TransferirSessionFull(int c1, int c2, float montante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Finalizar", ReplyAction="http://tempuri.org/IServico/FinalizarResponse")]
        void Finalizar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/TransferirSessionLess", ReplyAction="http://tempuri.org/IServico/TransferirSessionLessResponse")]
        void TransferirSessionLess(int c1, int c2, float montante);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoChannel : Ex4Cliente.b.ServiceReference1.IServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoClient : System.ServiceModel.ClientBase<Ex4Cliente.b.ServiceReference1.IServico>, Ex4Cliente.b.ServiceReference1.IServico {
        
        public ServicoClient() {
        }
        
        public ServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TransferirSessionFull(int c1, int c2, float montante) {
            base.Channel.TransferirSessionFull(c1, c2, montante);
        }
        
        public void Finalizar() {
            base.Channel.Finalizar();
        }
        
        public void TransferirSessionLess(int c1, int c2, float montante) {
            base.Channel.TransferirSessionLess(c1, c2, montante);
        }
    }
}
