//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Encomendas = new HashSet<Encomenda>();
            this.VendaProdutos = new HashSet<VendaProduto>();
        }
    
        public int ProdutoID { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Codigo { get; set; }
        public string Designacao { get; set; }
        public int StockQtd { get; set; }
        public int StockMinimo { get; set; }
        public float Preco { get; set; }
        public Nullable<int> Fornecedor_FornecedorID { get; set; }
    
        public virtual ICollection<Encomenda> Encomendas { get; set; }
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual ICollection<VendaProduto> VendaProdutos { get; set; }
    }
}
