//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendasPublisher.ServicoVendas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venda", Namespace="http://schemas.datacontract.org/2004/07/ASIVesteSedeAppLayer")]
    [System.SerializableAttribute()]
    public partial class Venda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoradaClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProduto {
            get {
                return this.IdProdutoField;
            }
            set {
                if ((this.IdProdutoField.Equals(value) != true)) {
                    this.IdProdutoField = value;
                    this.RaisePropertyChanged("IdProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoradaCliente {
            get {
                return this.MoradaClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.MoradaClienteField, value) != true)) {
                    this.MoradaClienteField = value;
                    this.RaisePropertyChanged("MoradaCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeCliente {
            get {
                return this.NomeClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeClienteField, value) != true)) {
                    this.NomeClienteField = value;
                    this.RaisePropertyChanged("NomeCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qtd {
            get {
                return this.QtdField;
            }
            set {
                if ((this.QtdField.Equals(value) != true)) {
                    this.QtdField = value;
                    this.RaisePropertyChanged("Qtd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoVendas.IVendaServico")]
    public interface IVendaServico {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVendaServico/enviaVenda")]
        void enviaVenda(VendasPublisher.ServicoVendas.Venda venda);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVendaServico/enviaVenda")]
        System.Threading.Tasks.Task enviaVendaAsync(VendasPublisher.ServicoVendas.Venda venda);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVendaServicoChannel : VendasPublisher.ServicoVendas.IVendaServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VendaServicoClient : System.ServiceModel.ClientBase<VendasPublisher.ServicoVendas.IVendaServico>, VendasPublisher.ServicoVendas.IVendaServico {
        
        public VendaServicoClient() {
        }
        
        public VendaServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VendaServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendaServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendaServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void enviaVenda(VendasPublisher.ServicoVendas.Venda venda) {
            base.Channel.enviaVenda(venda);
        }
        
        public System.Threading.Tasks.Task enviaVendaAsync(VendasPublisher.ServicoVendas.Venda venda) {
            return base.Channel.enviaVendaAsync(venda);
        }
    }
}
