//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendasPublisher.ServicoVendas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoVendas.IVendaServico")]
    public interface IVendaServico {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVendaServico/enviaVenda")]
        void enviaVenda(QueueVendas.VendaOrdem ordem);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVendaServico/enviaVenda")]
        System.Threading.Tasks.Task enviaVendaAsync(QueueVendas.VendaOrdem ordem);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVendaServicoChannel : VendasPublisher.ServicoVendas.IVendaServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VendaServicoClient : System.ServiceModel.ClientBase<VendasPublisher.ServicoVendas.IVendaServico>, VendasPublisher.ServicoVendas.IVendaServico {
        
        public VendaServicoClient() {
        }
        
        public VendaServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VendaServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendaServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendaServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void enviaVenda(QueueVendas.VendaOrdem ordem) {
            base.Channel.enviaVenda(ordem);
        }
        
        public System.Threading.Tasks.Task enviaVendaAsync(QueueVendas.VendaOrdem ordem) {
            return base.Channel.enviaVendaAsync(ordem);
        }
    }
}
