// <auto-generated />
namespace ASIVesteSede.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v0));
        
        string IMigrationMetadata.Id
        {
            get { return "201401292027317_v0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
