// <auto-generated />
namespace ASIVesteSede.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class V2Reclamacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V2Reclamacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201402091625402_V2-Reclamacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
