// <auto-generated />
namespace ASIVesteSede.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class V1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V1));
        
        string IMigrationMetadata.Id
        {
            get { return "201402031603571_V1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
