//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encomenda
    {
        public int Id { get; set; }
        public Nullable<int> ProdutoId { get; set; }
        public Nullable<bool> Recebida { get; set; }
        public int Qtd { get; set; }
        public Nullable<int> VendaId { get; set; }
    
        public virtual vProduto vProduto { get; set; }
    }
}
