//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public int Id { get; set; }
        public string NomeCliente { get; set; }
        public string MoradaCliente { get; set; }
        public int ProdutoId { get; set; }
        public Nullable<int> Qtd { get; set; }
        public bool Expedida { get; set; }
    
        public virtual vProduto vProduto { get; set; }
    }
}
