//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_verificarStock
    {
        public int Pid { get; set; }
        public int Fid { get; set; }
        public string Designacao { get; set; }
        public int StockQtd { get; set; }
        public int StockMinimo { get; set; }
    }
}
