//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex3
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlunosAssEst
    {
        public int NumAl { get; set; }
        public int nSeq { get; set; }
        public string Interesse { get; set; }
    
        public virtual Aluno Aluno { get; set; }
    }
}
